apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "uniquename"
  description: "asdfasdf"
  annotations:
    github.com/project-slug: aretli/uniquename1
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/demo-team"
